### ISSUE TITLE
webservice uri gives a 404 after setup

### ISSUE THREAD

**Issue by Gaya** [barrykooij/wp-simple-web-services#3]
After setting up my posts to be available via a REST call I get a 404.

![image](https://f.cloud.github.com/assets/970834/1662112/e51c32d4-5bf7-11e3-8f96-00cf20816335.png)

This is a screen of the config:

![image](https://f.cloud.github.com/assets/970834/1662118/f9443130-5bf7-11e3-93ef-f1b070e55b8d.png)

Might have something to do with the rewrites. Yes they are enabled.

**Comment by barrykooij** [comment]
Fixed in a1fdc4a54ed087b1f9be16738461e8b4e9a826d5
