### ISSUE TITLE
How to limit results?

### ISSUE THREAD

**Issue by khawarshzd** [barrykooij/wp-simple-web-services#8]
Hi 
I have installed the plugin and called the URL. I am getting results of all thousands of post. I want it in chunks of 10 posts per call. How to limit JSON results to 10?

**Comment by barrykooij** [comment]
Thanks for your suggestion report. This is not possible at the moment, but will be soon.
I'll keep you posted via this issue.

**Comment by barrykooij** [comment]
Version 1.1.0 will add support for default WP_Query vars in the get_posts web service. In your case adding the following to your web service request will solve the issue you're facing. `&qv[posts_per_page]=10`

Version 1.1.0 will be released in the next hour.

**Comment by barrykooij** [comment]
Version 1.1.0 has been released, update is available through your WordPress admin.
